  <link rel="stylesheet" href="static/styles/simplemodal.css">
  <link rel="stylesheet" href="static/styles/elements.css">
  <link rel="stylesheet" href="static/styles/layout.css">
  <link rel="stylesheet" href="static/styles/dropzone.css">
  <link rel="stylesheet" href="static/styles/filters.css">
  <link rel="stylesheet" href="static/styles/facet-list.css">
  <link rel="stylesheet" href="static/styles/library.css">
  <link rel="stylesheet" href="static/styles/item.css">
  <link rel="stylesheet" href="static/styles/metrics.css">
  <link rel="stylesheet" href="static/styles/item-edit.css">
  <link rel="stylesheet" href="static/styles/items.css">
  <link rel="stylesheet" href="static/styles/groups.css">
  <link rel="stylesheet" href="static/styles/tags.css">
  <link rel="stylesheet" href="static/styles/sync.css">
  <link rel="stylesheet" href="static/styles/search.css">
  <link rel="stylesheet" href="static/styles/app.css">
  <link rel="stylesheet" href="static/styles/screens.css">
  <!--<link rel="stylesheet" href="static/styles/text.css">-->
  <!--<link rel="stylesheet" href="static/styles/related.css">-->
  <link rel="stylesheet" href="static/styles/profile.css">
  <link rel="stylesheet" href="static/styles/plugins.css">
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lato:700">
